### ISSUE TITLE
WARLOCK Voidwalker Consume Shadows

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#535] opened 2021-02-01 12:52 UTC
Description:* Using Voidwalkers Consume shadows doesn't work.
How to reproduce: When I press the ability, The animation starts for a sec but stops. No health restored, No channel ongoing.
I've tried resummon my voidwalker, Logging in and out, yet no result.
How it should work: The Voidwalker consumes nearby shadows to bolster its form, recovering 310 health over 10 sec. 
Screenshot/video:

**Comment by cachocarne** [comment] 2021-02-23 09:33
I can confirm Consume Shadows is buggy. Very often you press on the ability and it does nothing. Even when standing on one spot and out of combat, it doesn't restore health and it doesn't give the increased stealth detection buff. Only way I managed to make it work is repeatedly making him PASSIVE and STAY, then it works most of the time. This should be fixed as soon as possible, it's a very important skill for PvP/Arenas.

**Comment by Vaxsysl** [comment] 2021-03-02 11:48
This ability doesn't work because Voidwalker starts to move when he beings channeling the ability, therefore stopping it. And sometimes, while he doesn't "move", he stops and TURNS on the spot, effectively stopping the channel of the ability. He has to be on passive and on stay command to make it work. And, while channeling it ,he's visually doing it at 3x speed too.

**Closed as completed** 2021-09-09 21:27 UTC
Labels: Fixed
