### ISSUE TITLE
[Warlock] Life Tap Scaling

### ISSUE THREAD

**Issue by Kupcakez** [SallyWhitemane/Mograine#138] opened 2020-12-19 18:18 UTC
**Description:**
Life tap is not scaling with spell power

**How to reproduce:**
Use life tap with a substantial amount of spell power and see the values aren't correct

**How it should work:**
As per tooltip, spell power should scale with how much mana is returned by life tap - thus, even at low ranks life tap can return a substantial amount of mana due to scaling with spell power

**Comment by SallyWhitemane** [comment] 2020-12-19 18:40
I've tested it and amount of mana added is the same as in the tooltip. Could you tell me how much spell power and which level do you have?

**Comment by Kupcakez** [comment] 2020-12-19 22:30
With 2361 spell power rank 1 life tap is suppose to give me back 1208 mana as per the tooltip - it currently is always giving me a flat 40 mana back but still taking 900 health

**Comment by Kupcakez** [comment] 2020-12-19 22:33
Seems to be only an issue with the lower ranks of life tap

**Comment by SallyWhitemane** [comment] 2020-12-20 15:49
Can't reproduce it, are you sure that you have shadow spell power here? 
![image](https://user-images.githubusercontent.com/74119436/102717539-4f471500-42e3-11eb-9fd3-2f219b4ca3c9.png)

**Comment by Kupcakez** [comment] 2020-12-20 16:12
![WoWScrnShot_122020_110839](https://user-images.githubusercontent.com/58132845/102718031-dc727580-42b3-11eb-9d21-ed40bb3a4b5e.jpg)

![WoWScrnShot_122020_111137](https://user-images.githubusercontent.com/58132845/102718066-222f3e00-42b4-11eb-8751-46994c9dd13c.jpg)

**Comment by Kupcakez** [comment] 2020-12-20 16:22
Also worth noting that you can kill yourself with lifetap

**Comment by SallyWhitemane** [comment] 2020-12-20 20:11
Issue will be fixed with next update, thanks for contribution!

**Closed as completed by SallyWhitemane** 2020-12-20 20:11 UTC
Labels: Fixed
