### ISSUE TITLE
[MAGE] T8 P2 bonus visual bug on tooltip

### ISSUE THREAD

**Issue by snurfisbugged** [SallyWhitemane/Mograine#1198] opened 2021-04-14 19:41 UTC
Hello

**Description:**
There's a visual bug on my mage. On the tooltip of either my gloves T8 (ilevel 219) or my head T8 (ilevel 226) (both equipped), i don't see the bonus 2 part activated. I think it's only visual because after some spells launched on training dummies, the buff "Praxis" https://wotlkdb.com/?spell=64868 do proc.

**How to reproduce:**
I've transmogged my new T8 Mage head just before equip it. Then put on head and gloves, and only gloves seems to be on the tooltip.

![issueKirinTor2P](https://user-images.githubusercontent.com/82540387/114768428-1e469080-9d69-11eb-8e4c-a1485d81a3f8.jpg)

**How it should work:**
The "Kirin Tor Hood" and the bonus 2P on the tooltip should be typed in white.

Thx : )

**Comment by scrublama** [comment] 2021-04-15 05:12
This is a visualbug with transmog to all classes and bonuses and not just mage. Also duplicate of many other reports

**Closed as completed** 2021-07-12 23:11 UTC
Labels: invalid
