### ISSUE TITLE
[NPC] Stoic Mammoth 30260

### ISSUE THREAD

**Issue by vut12** [SallyWhitemane/Mograine#1195] opened 2021-04-14 13:32 UTC
**Description:**
Two Stoic Mammoth spawn at all spawn points.

**How to reproduce:**
**How it should work:**
Only one npc should spawn at each point

**Comment by herbhenk** [comment] 2021-04-16 23:20
can confirm
https://imgur.com/a/jkJBjkS
the mammoth (https://wotlk-twinhead.twinstar.cz/?npc=30260) is spawning 2 mamoths instead of just 1 per spot

**Comment by scrublama** [comment] 2021-04-19 04:02
Duplicate of #864

**Closed as completed** 2021-09-07 00:03 UTC
Labels: Fixed, Npc-Issue
