### ISSUE TITLE
flight form and expert riding

### ISSUE THREAD

**Issue by tii86** [SallyWhitemane/Mograine#380] opened 2021-01-27 20:34 UTC
**Description:**
![image](https://user-images.githubusercontent.com/57909970/106050196-f6725580-60b4-11eb-9f36-128f31febe67.png)

When flight form is trained at 60, expert riding should be automatically learned. This is how it has worked on all previous wotlk servers. 

Only swift flight form requires the training to be purchased, and in that case the ability can only be learned after the riding skill is obtained.

**Comment by alexspew** [comment] 2021-01-27 20:52
Duplicate of https://github.com/SallyWhitemane/Mograine/issues/313

**Closed as completed** 2021-01-27 21:06 UTC
Labels: duplicate
